<?php

namespace AppBundle\Repository;

/**
 * CruisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruisesRepository extends \Doctrine\ORM\EntityRepository
{
}
