<?php

namespace AppBundle\Repository;

/**
 * RubricsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubricsRepository extends \Doctrine\ORM\EntityRepository
{
}
