<?php

namespace AppBundle\Repository;

/**
 * ToursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToursRepository extends \Doctrine\ORM\EntityRepository
{
}
