# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.continents:
        class: AppBundle\Admin\ContinentsAdmin
        arguments: [~, AppBundle\Entity\Continents, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Континенты }
    admin.countries:
        class: AppBundle\Admin\CountriesAdmin
        arguments: [~, AppBundle\Entity\Countries, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Страны }
    admin.cities:
        class: AppBundle\Admin\CitiesAdmin
        arguments: [~, AppBundle\Entity\Cities, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Города }
    admin.tours:
        class: AppBundle\Admin\ToursAdmin
        arguments: [~, AppBundle\Entity\Tours, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Туры }
    admin.contactform:
        class: AppBundle\Admin\ContactFormAdmin
        arguments: [~, AppBundle\Entity\ContactForm, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Почта }
